name: 'Sign File'

description: "Sign a file using SSL.com's CodeSignTool"

inputs:
  filepath:
    description: 'File to be signed'
    required: true
    # default: 'World'
  sslusername:
    description: 'SSL.com account username'
    required: true
  sslpassword:
    description: 'SSL.com account password'
    required: true
  sslsecretpassword:
    description: 'SSL.com account TOTP secret'
    required: true
  istest:
    description: 'When true, runs against SSL.com sandbox account'
    required: false
    default: false
runs:
  using: 'composite'
  steps:
    - name: Add masks
      run: |
        echo ::add-mask::${{ inputs.sslusername }}
        echo ::add-mask::${{ inputs.sslpassword }}
        echo ::add-mask::${{ inputs.sslsecretpassword }}
        echo ::add-mask::totp_secret
      shell: bash
    - name: Download and Setup CodeSignTool
      run: |

        if [ "$RUNNER_OS" == "Windows" ]; then
          curl https://www.ssl.com/download/29773/ --output CodeSignTool.zip
          dir
          choco install javaruntime
          7z x CodeSignTool.zip
          
          dir
          cd CodeSignTool-v1.2.0-windows
          dir
        else
          curl https://www.ssl.com/download/29764/ --output CodeSignTool.zip
          
          sudo apt-get install -y unzip
          sudo apt-get install -y default-jre
          unzip -o CodeSignTool.zip

          dir
          cd CodeSignTool-v1.2.0
          dir
        fi

      shell: bash
    - name: Sign File(s) Bash
      run: |
        if [ "$RUNNER_OS" == "Linux" ]; then
          dir
          cd CodeSignTool-v1.2.0

          dir
          mkdir -p "ssl-output"
          dir

          if [ ${{ inputs.istest }} = true ] ; then

            # TESTING ONLY - Sandbox creds

            printf "CLIENT_ID=qOUeZCCzSqgA93acB3LYq6lBNjgZdiOxQc-KayC3UMw\nOAUTH2_ENDPOINT=https://oauth-sandbox.ssl.com/oauth2/token\nCSC_API_ENDPOINT=https://cs-try.ssl.com\nTSA_URL=http://ts.ssl.com" > 'conf/code_sign_tool.properties'
            bash -eu CodeSignTool.sh sign -username="esigner_demo" -password="esignerDemo#1" -totp_secret="RDXYgV9qju+6/7GnMf1vCbKexXVJmUVr+86Wq/8aIGg=" -input_file_path="../miscellaneous/fake-file.ps1" -output_dir_path="ssl-output"

          else

            # SINGLE FILE
            bash -eu CodeSignTool.sh sign -username="${{ inputs.sslusername }}" -password="${{ inputs.sslpassword }}" -totp_secret="${{ inputs.sslsecretpassword }}" -input_file_path="${{ inputs.filepath }}" -output_dir_path="ssl-output"

          fi

          sudo cp -r ./ssl-output/* ../
        fi
      shell: bash
    - name: Sign File(s) PWSH
      run: |
        Write-Host $Env:OS
        Write-Host "----------"
        Get-Item -Path Env:* | Get-Member
        Write-Host "----------"
        Write-Host $Env:*
        Write-Host "----------"


        if ($Env:OS -like "*Windows*")
        {
          dir
          cd CodeSignTool-v1.2.0-windows
          
          dir
          mkdir -p "ssl-output"
          dir

          if ($inputs:istest -eq $true)
          {
            # TESTING ONLY - Sandbox creds    

            printf "CLIENT_ID=qOUeZCCzSqgA93acB3LYq6lBNjgZdiOxQc-KayC3UMw\nOAUTH2_ENDPOINT=https://oauth-sandbox.ssl.com/oauth2/token\nCSC_API_ENDPOINT=https://cs-try.ssl.com\nTSA_URL=http://ts.ssl.com" > 'conf/code_sign_tool.properties'
            .\CodeSignTool.bat sign -username="esigner_demo" -password="esignerDemo#1" -totp_secret="RDXYgV9qju+6/7GnMf1vCbKexXVJmUVr+86Wq/8aIGg=" -input_file_path="../miscellaneous/fake-file.ps1" -output_dir_path="ssl-output"  
          }
          else
          {
            # SINGLE FILE
            .\CodeSignTool.bat sign -username="$inputs:sslusername" -password="$inputs:sslpassword" -totp_secret="$inputs:sslsecretpassword" -input_file_path="$inputs:filepath" -output_dir_path="ssl-output"

          }
          dir ..\
          Copy-Item -Path ".\ssl-output\*" -Destination "..\" -Recurse
          dir ..\
        }
      shell: pwsh
